name: rcm_prevention
version: "1.0.0"
config-version: 2

profile: rcm_prevention

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rcm_prevention:
    staging:
      +schema: STAGING
      +materialized: view
      +tags: ["staging"]
    marts:
      +schema: MART
      +materialized: table
      +tags: ["mart"]
